Invoking command in '/home/steve/workspaces/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/src/maze_bot': PYTHONPATH=/home/steve/workspaces/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/install/maze_bot/lib/python3.8/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py egg_info --egg-base ../../build/maze_bot build --build-base /home/steve/workspaces/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/build/maze_bot/build install --prefix /home/steve/workspaces/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/install/maze_bot --record /home/steve/workspaces/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/build/maze_bot/install.log --single-version-externally-managed
Invoked command in '/home/steve/workspaces/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/src/maze_bot' returned '0': PYTHONPATH=/home/steve/workspaces/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/install/maze_bot/lib/python3.8/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py egg_info --egg-base ../../build/maze_bot build --build-base /home/steve/workspaces/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/build/maze_bot/build install --prefix /home/steve/workspaces/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/install/maze_bot --record /home/steve/workspaces/ROS2-Path-Planning-and-Maze-Solving/path_planning_ws/build/maze_bot/install.log --single-version-externally-managed
